name: "Build and Test"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    path-ignore:
      - ./**/*.md
  pull_request:
    path-ignore:
      - ./**/*.md

jobs:
  build_and_test:
    name: "Build and test"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Checkout
        uses: actions/checkout@v3
      - run: npm i
        name: Install deps
      - run: npm run build
        name: Build
      - run: npm run test
        name: Test
