name: "Build and Test"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    path-ignore:
      - ./**/*.md
  pull_request:
    path-ignore:
      - ./**/*.md

jobs:
  build_and_test:
    name: "Build and Test"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Checkout
        uses: actions/checkout@v3
      - run: npm i
        name: Install deps
      - run: npm run build
        name: Build
      - run: npm run test
        name: Test
  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build_and_test
    name: "Commit and push to prd"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: prd
      - run: git fetch && git rebase main
        name: Update prd branch
      - run: npm i
        name: Install deps
      - run: npm run build
        name: Build
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'release: auto commit'
          branch: prd
          push_options: '--force'
          file_pattern: out/app.js index.html index.css
          commit_user_name: bot-vtno
          commit_user_email: tino@vtno.me
          commit_author: vtno <tino@vtno.me>
          skip_checkout: true
